# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layer_source', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MXD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('path', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('client', models.CharField(max_length=10)),
                ('created_by', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('layer_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layer_source.Layer_Source')),
            ],
            options={
                'verbose_name': 'MXD',
            },
        ),
    ]
