# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layer_source', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MXD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('path', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('created_on', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MXD',
            },
        ),
        migrations.CreateModel(
            name='MXD_Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MXD Client',
            },
        ),
        migrations.CreateModel(
            name='MXD_Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MXD Creator',
            },
        ),
        migrations.AddField(
            model_name='mxd',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mxd.MXD_Client'),
        ),
        migrations.AddField(
            model_name='mxd',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mxd.MXD_Creator'),
        ),
        migrations.AddField(
            model_name='mxd',
            name='layer_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layer_source.Layer_Source'),
        ),
    ]
