# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mxd', '0002_auto_20170201_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='MXD_Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MXD Client',
            },
        ),
        migrations.CreateModel(
            name='MXD_Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MXD Creator',
            },
        ),
        migrations.AlterField(
            model_name='mxd',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mxd.MXD_Client'),
        ),
        migrations.AlterField(
            model_name='mxd',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mxd.MXD_Creator'),
        ),
    ]
