# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer_source', '0003_layer_source_owner'),
        ('mxd', '0002_auto_20170213_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mxd',
            name='layer_source',
        ),
        migrations.AddField(
            model_name='mxd',
            name='layer_source',
            field=models.ManyToManyField(to='layer_source.Layer_Source'),
        ),
    ]
