# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_adapter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_adapter',
            name='alias',
            field=models.CharField(max_length=40),
        ),
    ]
