# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_adapter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='web_adapter',
            options={'ordering': ['machine_name'], 'verbose_name': 'Web Adapter'},
        ),
        migrations.AlterField(
            model_name='web_adapter',
            name='enviroment',
            field=models.CharField(max_length=20),
        ),
    ]
