# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_adapter', '0002_auto_20170201_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_adapter',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
