# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGOL_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('creator', models.CharField(max_length=20)),
                ('comments', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ArcGIS Online Item',
            },
        ),
        migrations.CreateModel(
            name='AGOL_Item_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ArcGIS Online Item Type',
            },
        ),
        migrations.AddField(
            model_name='agol_item',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agol.AGOL_Item_Type'),
        ),
        migrations.AddField(
            model_name='agol_item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
