# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mxd', '0001_initial'),
        ('agol_users', '0001_initial'),
        ('web_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGOL_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('external_layer_url', models.URLField()),
                ('comments', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('mxd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mxd.MXD', verbose_name='MXD')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agol_users.AGOL_User')),
            ],
            options={
                'verbose_name': 'ArcGIS Online Item',
            },
        ),
        migrations.CreateModel(
            name='AGOL_Item_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ArcGIS Online Item Type',
            },
        ),
        migrations.AddField(
            model_name='agol_item',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agol.AGOL_Item_Type'),
        ),
        migrations.AddField(
            model_name='agol_item',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_service.Web_Service'),
        ),
    ]
