# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agol', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agol_item',
            old_name='user',
            new_name='owner',
        ),
    ]
