# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agol', '0002_auto_20170201_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agol_item',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
