# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agol', '0002_auto_20170213_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agol_item',
            options={'ordering': ['name'], 'verbose_name': 'ArcGIS Online Item'},
        ),
        migrations.AlterModelOptions(
            name='agol_item_type',
            options={'ordering': ['type'], 'verbose_name': 'ArcGIS Online Item Type'},
        ),
    ]
