# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agol', '0003_auto_20170201_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agol_item',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_service.Web_Service'),
        ),
    ]
