# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agol', '0004_auto_20170201_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agol_item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mxd.MXD'),
        ),
    ]
