# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mxd', '0002_auto_20170201_1701'),
        ('agol', '0006_auto_20170201_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agol_item',
            name='creator',
        ),
        migrations.AddField(
            model_name='agol_item',
            name='mxd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mxd.MXD', verbose_name='MXD'),
            preserve_default=False,
        ),
    ]
