# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agol', '0007_auto_20170202_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='agol_item',
            name='external_layer_url',
            field=models.URLField(default='http://www.abc.com.au/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agol_item',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
