# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agol_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agol_user',
            options={'ordering': ['name'], 'verbose_name': 'AGOL User'},
        ),
    ]
