# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('purpose', models.CharField(max_length=50)),
                ('collector', models.BooleanField()),
                ('collector_offline', models.BooleanField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webmap_App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('purpose', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webmap App',
            },
        ),
        migrations.CreateModel(
            name='Webmap_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webmap Contact',
            },
        ),
        migrations.CreateModel(
            name='Webmap_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('map_description', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('agol_item', models.ManyToManyField(to='agol.AGOL_Item')),
                ('webmap', models.ManyToManyField(to='webmap.Webmap')),
            ],
            options={
                'verbose_name': 'Webmap Item',
            },
        ),
        migrations.AddField(
            model_name='webmap_app',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmap.Webmap_Contact'),
        ),
        migrations.AddField(
            model_name='webmap_app',
            name='webmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmap.Webmap'),
        ),
        migrations.AddField(
            model_name='webmap',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmap.Webmap_Contact'),
        ),
    ]
