# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webmap_item',
            old_name='agol_item',
            new_name='agol',
        ),
        migrations.RemoveField(
            model_name='webmap_item',
            name='map_description',
        ),
        migrations.AddField(
            model_name='webmap_item',
            name='description',
            field=models.TextField(blank=True, verbose_name='Map description'),
        ),
    ]
