# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webmap_item',
            old_name='map_comments',
            new_name='map_description',
        ),
        migrations.AddField(
            model_name='webmap_item',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
