# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0002_auto_20170213_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webmap',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='webmap',
            name='purpose',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='webmap_app',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='webmap_app',
            name='purpose',
            field=models.CharField(max_length=255),
        ),
    ]
