# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0003_auto_20170213_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webmap',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='webmap_app',
            options={'ordering': ['name'], 'verbose_name': 'Webmap App'},
        ),
        migrations.AlterModelOptions(
            name='webmap_contact',
            options={'ordering': ['contact_name'], 'verbose_name': 'Webmap Contact'},
        ),
        migrations.AlterModelOptions(
            name='webmap_item',
            options={'ordering': ['name'], 'verbose_name': 'Webmap Item'},
        ),
    ]
