# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0003_auto_20170202_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webmap_contact',
            options={'verbose_name': 'Webmap Contact'},
        ),
    ]
