# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0004_auto_20170202_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webmap_app',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmap.Webmap_Contact'),
        ),
    ]
