# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0004_auto_20170313_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webmap_app',
            name='url',
            field=models.URLField(help_text='URL of the web mapping application'),
        ),
    ]
