# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0005_auto_20170313_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='webmap',
            name='url',
            field=models.URLField(default='http://This.URL.Is.Required/', help_text='URL of the web map'),
            preserve_default=False,
        ),
    ]
