# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-21 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0008_prepare_to_remove_webmap_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webmap_item',
            name='agol',
        ),
        migrations.RemoveField(
            model_name='webmap_item',
            name='webmap',
        ),
        migrations.DeleteModel(
            name='Webmap_Item',
        ),
    ]
