# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mxd', '0001_initial'),
        ('web_adapter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('actual_url', models.URLField()),
                ('alias_url', models.URLField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('mxd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mxd.MXD')),
                ('web_adapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_adapter.Web_Adapter')),
            ],
        ),
    ]
