# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_service_level',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='web_service_level',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
