# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0003_auto_20170313_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_service',
            name='alias_url',
            field=models.URLField(help_text='Full URL of layer / web service that includes the alias to the actual machine name of host machine that ArcGIS Server (which creates/contains the web services) resides.  Note that if only one layer is defined in the web service then put the full URL including the index number of that layer.  Else, include no index numbers Eg. https://arcgis.dpaw.wa.gov.au/arcgis/rest/services/PVS/Long_Trails_Structures_WSE/MapServer/0'),
        ),
        migrations.AlterField(
            model_name='web_service',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
