# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webmap', '0001_initial'),
        ('agol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('agol', models.ManyToManyField(to='agol.AGOL_Item')),
                ('webmap', models.ManyToManyField(to='webmap.Webmap')),
                ('webmap_app', models.ManyToManyField(to='webmap.Webmap_App')),
            ],
            options={
                'verbose_name': 'Group',
            },
        ),
    ]
