# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'AGOL Group'},
        ),
    ]
