# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layer_source', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer_source_format_type',
            options={'verbose_name': 'Layer Source Feature Type'},
        ),
    ]
