# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer_source', '0002_auto_20170213_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer_source',
            name='owner',
            field=models.CharField(default='blank', max_length=40),
            preserve_default=False,
        ),
    ]
