# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer_source', '0003_layer_source_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer_source',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
